import 'package:flutter/material.dart';
import 'package:oiopay/color_scheme.dart';

class Paymentmethod extends StatefulWidget {
  const Paymentmethod({super.key});

  @override
  // ignore: library_private_types_in_public_api
  _PaymentmethodState createState() => _PaymentmethodState();
}

class _PaymentmethodState extends State<Paymentmethod> {
    final mycolor = Mycolor();

  List<Widget> widgets = []; // List to hold widgets


@override
  void initState() {
    super.initState();
    // Add initial widgets to the list
    for (var i = 0; i < 5; i++) {
      widgets.addAll([returnCard()]);
    }
        
   
  
  }


  @override
  Widget build(BuildContext context) {
    return Scaffold(

 // BACKGROUND COLOR
      backgroundColor: mycolor.backgroundColor,
    
    //  NEW APP BAR
      appBar: AppBar(
        backgroundColor: mycolor.appBar,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back_ios_new),
          onPressed: () {
            Navigator.pop(context);
          },
        ),
        title: const Text('Payment Methods',
        textScaler: TextScaler.noScaling,
        style: TextStyle(
          fontSize: 22,
        ),
        ),
        centerTitle: true,
      ),
    
    
    
    

      body: SingleChildScrollView(
        child: Column(
          children: [

            const SizedBox(height: 20,),
            // Existing widgets
            ...widgets,
            // SizedBox with GestureDetector to add new widget
           


          Padding(
       padding: const EdgeInsets.fromLTRB(12, 0, 12, 12),
       child: SizedBox(
        
        height: 150,
        width: double.infinity,
        child: Card(
          
          elevation: 5,
          shape:const CircleBorder(),
         color: mycolor.appBar, 
          child:  GestureDetector(
             onTap: () {
                  
      setState(() {
                    // Add a new widget generated by the createWidget function
                    widgets.add(returnCard());
                  });
    },
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.center,
              children: [
               const Spacer(),
               
                Icon(Icons.add_card,
                color: mycolor.backgroundColor,
                size: 60,),
              
                  Text("Add New\nCard",
                  textAlign:TextAlign.center,
                   textScaler: TextScaler.noScaling,
                  style: TextStyle(color: mycolor.backgroundColor,
                  fontSize: 20,
                  fontWeight: FontWeight.w500,
                  ),
                  
                  ),
               

              const Spacer(),
                 
                
              ],
            ),
          ),
        ),
       ),
         ),


          ],
        ),
      ),
    );
  }







  // Function to create a new widget
  
Widget returnCard(){  
  return Column(
    mainAxisAlignment: MainAxisAlignment.center,
    children: [
      const Text("Data",
      textScaler: TextScaler.noScaling,
      style: TextStyle(
        fontSize: 20,
      ),),

      SizedBox(
        height:300,
        child: Stack(
            children: [
      
      
                   Positioned(
                    top: 165,
                    child: Container(
                    height: 100,
                    width: 375,
                    decoration:  BoxDecoration(
                      color: Colors.transparent,
                      border: Border.all(
            color: Colors.black, // Set border color
            width: 0.5, // Set border width
          ),
                    
        
                      shape: BoxShape.rectangle,
                      borderRadius: const BorderRadius.all(Radius.circular(30)),
                    ),
        
        
                    child: Stack(
                      children: [
        
                        Positioned(
                          top: 55,
                          child: Row(
                          
                            children: [
        
                               const SizedBox(width: 30,),
        
                          // EDIT TEXT BUTTON
                          TextButton.icon(
        onPressed: () {
          // Add your onPressed logic here
        },
        icon:  Icon(Icons.edit,
                      color: mycolor.appBar,), // Specify the icon
        label:    Text("Edit",
                           textScaler: TextScaler.noScaling,
                          style: TextStyle(color: mycolor.appBar,
                          fontSize: 25,
                          
                          
                          fontWeight: FontWeight.w400,
                          ),
                          
                          ), // Specify the text label
        ),
        
        
        
        
        
        
        
                 const SizedBox(width: 20,),
                    // Seperator
                                        Container(
                      width:0.5, // Set the width of the separator
                      height: 30, // Set the height of the separator
                      color: Colors.grey, // Set the color of the separator
                    ),
                          
        
        
            const SizedBox(width: 20,),
        
                  // DELETE TEXT BUTTON
                          TextButton.icon(
        onPressed: () {
          // Add your onPressed logic here
        },
        icon:  Icon(Icons.delete,
                      color: mycolor.appBar,), // Specify the icon
        label:    Text("Delete",
                           textScaler: TextScaler.noScaling,
                          style: TextStyle(color: mycolor.appBar,
                          fontSize: 25,
                          
                          
                          fontWeight: FontWeight.w400,
                          ),
                          
                          ), // Specify the text label
        ),
                  
                       
                                    
                            ],
                          ),
                        ),
                      ],
                    ),
                   )),
        
        
        
        
        
              //   Card
                   GestureDetector(
                        
                     onTap: () {
                        Navigator.push(
                          context,
                          MaterialPageRoute(builder: (context) => const Paymentmethod()),
                        );
                      },
                      
                     child: SizedBox(
                       width: 375,
                       height: 220,
                       child: Card(
                        shadowColor: mycolor.primaryColor,
                       shape:const RoundedRectangleBorder(borderRadius: BorderRadius.all(Radius.circular(20))),
                         elevation: 10,
                                 child: Container(
                                  
                                     decoration:  BoxDecoration(
                                  borderRadius:  BorderRadius.circular(20),
                               gradient:  LinearGradient(
                                colors: [ const Color.fromRGBO(83, 197, 250, 1),  mycolor.gradient], // Example gradient colors
                     stops: const [0.1, 0.8], // Stops at 20% and 80% of the gradient
                     begin: Alignment.topCenter,
                     end: Alignment.bottomRight,
                               ),
                             ),
                                   child:  Column(
                                     children: [
                                  
                                  
                                  
                                       const SizedBox(height: 20,),
                                  
                                 // 1st top ROW
                                           Row(
                                           
                                   
                                         children: [
                                  
                                  
                                           const SizedBox( width: 25,),
                                                Text("My Cards",
                                                 textScaler: TextScaler.noScaling,
                                       style: TextStyle(color: mycolor.backgroundColor,
                                       fontSize: 18,
                                       
                                       ),
                                       
                                       ),
                                   
                                       const Spacer(),
                                  
                                  
                                           Text("OIO PAY",
                                           textScaler: TextScaler.noScaling,
                                       style: TextStyle(color: mycolor.backgroundColor,
                                       fontSize: 23,
                                       fontWeight: FontWeight.bold,
                                       ),
                                       
                                       ),
                                  
                                       const SizedBox(width: 30,),
                                  
                                         ] 
                                       ),
                                  
                                  
                                       const SizedBox(height: 18,),
                                  
                                  
                                  
                                  
                                       // 2nd Row
                                      
                                   Row(
                                   children: [
                                  
                                       const SizedBox(width: 40,),
                                  
                                     Container(
                                       
                                       color:const Color.fromRGBO(255, 237, 103, 1),
                                       child: const Placeholder(
                                       fallbackHeight: 25,
                                       fallbackWidth: 40,
                                     
                                       
                                       color: Color.fromRGBO(236, 222, 120, 1),
                                       
                                       ),
                                     ),
                                     
                                     const SizedBox(width: 8,),
                                  
                                     const Icon(Icons.face_retouching_natural_outlined,
                                     size: 35,
                                     color: Color.fromRGBO(236, 222, 120, 1),
                                     )
                                  
                                   ],
                                   ),
                                  
                                   const SizedBox(height: 10,),
                                  
                                   const Row(
                                     
                                   
                                  
                                   ),
                                  
                                   // 3rd row
                                  
                                  Row(
                                   children: [
                                  
                                     const SizedBox(width: 30,),
                                  
                                    Text("1234  4568  1234  5689",
                                    textScaler:TextScaler.noScaling,
                                    style: TextStyle(
                                     fontSize: 23,
                                     color: mycolor.backgroundColor,
                                     fontWeight:FontWeight.w400,
                                     
                                    ),
                                     
                                    ),
                                   ],
                                  
                                 ),
                                  
                                  const SizedBox(height: 5,),
                                  
                                 const Row(
                                   children: [
                                       SizedBox(width: 26,),
                                     Text(
                                       "USER NAME",
                                       textScaler: TextScaler.noScaling,
                                       style: TextStyle(
                                         fontSize: 17,
                                         color: Colors.white,
                                         fontWeight: FontWeight.w500
                                       ),
                                     ),
                                  
                                     Spacer(),
                                  
                                     Column(
                                       children: [
                                         Text("VALID THRU",
                                         textScaler: TextScaler.noScaling,
                                         style: TextStyle(
                                           fontSize: 13,
                                           color: Colors.white,
                                         ),
                                         ),
                                  
                                         Text("00/00",
                                         textScaler:TextScaler.noScaling ,
                                         style: TextStyle(
                                        
                                           fontSize: 12,
                                           color: Colors.white,
                                         ),
                                         )
                                  
                                      
                                       ],
                                  
                                     ),
                                      SizedBox(width: 30,),
                                   ],
                                 ),
                                  
                                     ]
                                     
                                    
                                   ),
                                 ),
                        
                       ),
                     ),
                   ),
            ],
        ),
      ),
    ],
  );
}

}
